#!/usr/bin/env bash
#
# Snapshot the Copilot CLI version + per-platform npm integrity values for the
# rust crate's bundled-in-process build path.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUST_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${RUST_DIR}/.." && pwd)"
LOCKFILE="${REPO_ROOT}/nodejs/package-lock.json"
OUTPUT="${RUST_DIR}/cli-version-in-process.txt"

if [[ ! -f "${LOCKFILE}" ]]; then
  echo "error: ${LOCKFILE} not found" >&2
  exit 1
fi

VERSION="$(node -e "console.log(require('${LOCKFILE}').packages['node_modules/@github/copilot'].version)")"
if [[ -z "${VERSION}" ]]; then
  echo "error: could not read @github/copilot version from ${LOCKFILE}" >&2
  exit 1
fi

PACKAGES=(
  "copilot-darwin-arm64"
  "copilot-darwin-x64"
  "copilot-linux-arm64"
  "copilot-linux-x64"
  "copilot-linuxmusl-arm64"
  "copilot-linuxmusl-x64"
  "copilot-win32-arm64"
  "copilot-win32-x64"
)

declare -A INTEGRITIES
for package in "${PACKAGES[@]}"; do
  integrity="$(node -e "console.log(require('${LOCKFILE}').packages['node_modules/@github/${package}'].integrity)")"
  if [[ -z "${integrity}" ]]; then
    echo "error: package-lock.json missing integrity for @github/${package}" >&2
    exit 1
  fi
  INTEGRITIES[$package]="${integrity}"
done

{
  echo "# Auto-generated by rust/scripts/snapshot-bundled-in-process-version.sh"
  echo "# Do not edit. Regenerated by the publish workflow on every release."
  echo "version=${VERSION}"
  for package in "${PACKAGES[@]}"; do
    echo "${package}=${INTEGRITIES[$package]}"
  done
} > "${OUTPUT}"

echo "Wrote ${OUTPUT} (version=${VERSION}, ${#PACKAGES[@]} integrity values)"
